// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3FZwasCvN86bSgqA8DmJ_LoY1hyKgb8Y',
    appId: '1:644513652198:web:26c6a5e9663f21563eca27',
    messagingSenderId: '644513652198',
    projectId: 'strivo-9505e',
    authDomain: 'strivo-9505e.firebaseapp.com',
    storageBucket: 'strivo-9505e.firebasestorage.app',
    measurementId: 'G-MXE9QLSH6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDADr3Jxlhr58Bsbz-eiWymbXnzEHpXwMQ',
    appId: '1:644513652198:android:71575968dd8a55293eca27',
    messagingSenderId: '644513652198',
    projectId: 'strivo-9505e',
    storageBucket: 'strivo-9505e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE1UtuBrQVWvz5nl6xPFvVHobGBy0cipU',
    appId: '1:644513652198:ios:bcec783743f39fa63eca27',
    messagingSenderId: '644513652198',
    projectId: 'strivo-9505e',
    storageBucket: 'strivo-9505e.firebasestorage.app',
    iosBundleId: 'com.example.strivo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE1UtuBrQVWvz5nl6xPFvVHobGBy0cipU',
    appId: '1:644513652198:ios:bcec783743f39fa63eca27',
    messagingSenderId: '644513652198',
    projectId: 'strivo-9505e',
    storageBucket: 'strivo-9505e.firebasestorage.app',
    iosBundleId: 'com.example.strivo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3FZwasCvN86bSgqA8DmJ_LoY1hyKgb8Y',
    appId: '1:644513652198:web:bfb1dd1977d89f8e3eca27',
    messagingSenderId: '644513652198',
    projectId: 'strivo-9505e',
    authDomain: 'strivo-9505e.firebaseapp.com',
    storageBucket: 'strivo-9505e.firebasestorage.app',
    measurementId: 'G-YGB5NTZ1CK',
  );
}
